### ISSUE TITLE
Deleting a load balancer in the console destroys state

### ISSUE THREAD

**Issue by DanielMSchmidt** [hetznercloud/terraform-provider-hcloud#199]
I provisioned a load balancer with targets set directly on the LB and refactored it to use the load_balancer_target resource instead as I wanted to ensure the load balancer stays alive when the underlying servers change. This change lead to an error saying the target was already configured. As a solution I removed the load balancer in the admin console, leading to an error:

```
Error: no load balancer with id ....
```

This breaks the state, I can neither destroy nor do anything else, I need to remove everything by hand and reset the TF state

**Comment by DanielMSchmidt** [comment]
If someone else runs into this: `terraform state list` and `terraform state rm` might be helpful recovering this situation without the need to nuke everything

**Comment by LKaemmerling** [comment]
Hey @DanielMSchmidt, your issues exists because of two problems. The first one (target already configured) will be fixed with the next release. The second one is not a problem:

The targets (and services) rely on the load balancer, so if you delete the load balancer the targets (and services) should also be deleted too.

**Comment by LKaemmerling** [comment]
Should be fixed with v1.19.2
