### ISSUE TITLE
Better way to install / use this provider

### ISSUE THREAD

**Issue by pstadler** [hetznercloud/terraform-provider-hcloud#20]
Wondering whether there's a way to automatically obtain this provider during `terraform init`. If that's not the case, are there any plans to integrate it more tightly into the ecosystem?

I'm planning to introduce Hetzner Cloud as the favorite choice for small scale Kubernetes clusters[1]. So far everything runs well using CX11 instances.

[1] https://github.com/hobby-kube/guide/issues/28

**Comment by thetechnick** [comment]
Hi @pstadler,
we are already in contact with Hashi Corp to integrate our provider in Terraform, but this may take a while... Until then the provider needs to be installed from the binaries.

Since yesterday this provider is listed under the Terraform community providers (It's a start):
https://www.terraform.io/docs/providers/type/community-index.html

**Comment by pstadler** [comment]
Good to hear. I actually checked this page just before opening this issue. Maybe we could use this issue for tracking the progress?

**Comment by thetechnick** [comment]
Sure, I will leave this issue open and post updates when there are news.

**Comment by pstadler** [comment]
Cool 👍

**Comment by thetechnick** [comment]
Initial review: https://github.com/hetznercloud/terraform-provider-hcloud/issues/34

**Comment by thetechnick** [comment]
https://www.terraform.io/docs/providers/hcloud/index.html :tada:
