### ISSUE TITLE
Switching 'network_id' to 'subnet_id' in 'hcloud_server_network' block forces replacement

### ISSUE THREAD

**Issue by danielgrant** [hetznercloud/terraform-provider-hcloud#236]
Terraform version: `0.13.2`
hcloud provider version: `1.20.1`

The change that introduced this issue came in as part of `1.19.2`: https://github.com/hetznercloud/terraform-provider-hcloud/releases/tag/v1.19.2 

Actual resource names and ID's are obfusticated to protect the innocent.

**Context**

After upgrading to Terraform `0.13.2` and hcloud provider `1.20.1`, a `terraform validate` informs me that the attribute `network_id` in `hcloud_server_network` blocks is deprecated and has been replaced by `subnet_id`:

```
Warning: "network_id": [DEPRECATED] use subnet_id instead

  on network.tf line 19, in resource "hcloud_server_network" "my_resource_1":
  19: resource "hcloud_server_network" "my_resource_1" {

(and 2 more similar warnings elsewhere)

Success! The configuration is valid, but there were some validation warnings as shown above.
```

**Expected result**

After switching the attriubte name to `subnet_id` and referencing the `id` attribute of the corresponding `hcloud_network_subnet` (instead of `hcloud_network`, as it was with `network_id`), the hcloud Terraform provider should report no changes in the resources.

This is because we're not actually changing what underlying subnet the `hcloud_server_network` is attached to - we're simply pointing to the existing subnet instead of the network, in order to resolve a race condition (as per the release notes).

This should not cause Terraform to report any changes at all, or at a minimum should report changes that do not require the resource to be destroyed and recreated.

**Actual result**

Terraform attempts to recreate the entire `hcloud_server_network` resources due to changing the deprecated `network_id` attribute with its replacement `subnet_id` attribute:

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # hcloud_server_network.bastion_servertex_com must be replaced
-/+ resource "hcloud_server_network" "my_resource_1" {
      - alias_ips   = [] -> null
      ~ id          = "xxxxxxx-xxxx" -> (known after apply)
        ip          = "x.x.x.x"
      ~ mac_address = "xx:xx:xx:xx:xx:xx" -> (known after apply)
      - network_id  = xxxx -> null # forces replacement
        server_id   = xxxxxxx
      + subnet_id   = "xxxx-x.x.x.x/24" # forces replacement
    }

  # hcloud_server_network.irc_servertex_com must be replaced
-/+ resource "hcloud_server_network" "my_resource_2" {
      - alias_ips   = [] -> null
      ~ id          = "xxxxxxx-xxxx" -> (known after apply)
        ip          = "x.x.x.x"
      ~ mac_address = "xx:xx:xx:xx:xx:xx" -> (known after apply)
      - network_id  = xxxx -> null # forces replacement
        server_id   = xxxxxxx
      + subnet_id   = "xxxx-x.x.x.x/24" # forces replacement
    }

  # hcloud_server_network.web_servertex_com must be replaced
-/+ resource "hcloud_server_network" "my_resource_3" {
      - alias_ips   = [] -> null
      ~ id          = "xxxxxxx-xxxx" -> (known after apply)
        ip          = "x.x.x.x"
      ~ mac_address = "xx:xx:xx:xx:xx:xx" -> (known after apply)
      - network_id  = xxxx -> null # forces replacement
        server_id   = xxxxxxx
      + subnet_id   = "xxxx-x.x.x.x/24" # forces replacement
    }

Plan: 3 to add, 0 to change, 3 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

Note that there may also be a typo in the release notes - they state that this introduces `subnet_ip` as a replacement for `network_id`, but Terraform reports that `subnet_id` is the replacement attribute name?

**Comment by fhofherr** [comment]
Hi @danielgrant,

unfortunately this is the case, as the introduction of a new property changes the Terraform state. The way our API currently works we need to use `ForceNew` for the `network_id` and `subnet_id` properties in case a user actually wants to change the network assignment of a server.

The recreation of the `hcloud_server_network` resource leads to a brief moment where the server is not reachable. We understand that this may not be desirable for users that did not really change the network assignment. Removing the `network_id` property would have been a backwards incompatible change. We therefore merely marked it as deprecated. It remains to function just as it always did. There is no intention of removing it before a 2.0 release, which as of now is not planned. 

However, since there has been some confusion about the naming of the property. Quite a few users were bitten by the fact that resources currently do not get assigned to the selected subnet, unless an IP within that subnet is additionally specified. We therefore decided to un-deprecate the `network_id` property for the time being. Please note, that we may deprecate it again in a future release of the Terraform provider. In this case the issue may resurface, but the deprecated property will continue to function until we remove it entirely, which will only happen in a new major release.
