### ISSUE TITLE
Protected Load Balancer gets edited but terraform loses track

### ISSUE THREAD

**Issue by ambis** [hetznercloud/terraform-provider-hcloud#320]
```
cat .terraform.lock.hcl
provider "registry.terraform.io/hetznercloud/hcloud" {
  version     = "1.24.0"
```

I had enabled Protection in the UI for my Load Balancer.

I changed the IP of the loadbalancer with Terraform:

```
  # module.cloud.hcloud_load_balancer_network.nat_network_load_balancer must be replaced
-/+ resource "hcloud_load_balancer_network" "nat_network_load_balancer" {
      ~ id                      = "1234-1234" -> (known after apply)
      ~ ip                      = "10.0.0.3" -> "10.0.0.5" # forces replacement
        # (3 unchanged attributes hidden)
    }
```

After this change, I started getting

```
terraform apply
Error: load balancer target not found
```

I had to manually delete the LB resources from TF state & UI and then apply them again. 

If I try to edit a Protected server, the library tells me that protection is on and does not do anything. It should do a similar thing with LoadBalancers.

**Comment by LKaemmerling** [comment]
Hey @ambis,

this should be basically fixed with https://github.com/hetznercloud/terraform-provider-hcloud/pull/322. The protection you enable does not apply to the specific configuration of a Load Balancer (or a server). The protection only protects against unwanted deletion (and rebuilding for servers).
