### ISSUE TITLE
Support load-balancer certificate management

### ISSUE THREAD

**Issue by StarpTech** [hetznercloud/terraform-provider-hcloud#341]
Hi, it would be great to have support for:

- Set tls mode of the load-balancer
- Create let's encrypt certificates
- Assign custom certificates

Related: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/178

**Comment by LKaemmerling** [comment]
Hey @StarpTech,

this is already possible. You can create Let`s Encrypt certificates since v1.26.0: https://github.com/hetznercloud/terraform-provider-hcloud/releases/tag/v1.26.0 
Setting the `tls-mode` is also easily possible. In the cloud console this just reflects an template for a service definition like:
```
resource "hcloud_load_balancer" "load_balancer" {
  name       = "my-load-balancer"
  load_balancer_type = "lb11"
  location   = "nbg1"
}
resource "hcloud_managed_certificate" "managed_cert" {
    name        = "managed_cert"
    domain_names = ["*.example.com", "example.com"]
    labels = {
        label_1 = "value_1"
        label_2 = "value_2"
    }
}
resource "hcloud_load_balancer_service" "load_balancer_service" {
    load_balancer_id = hcloud_load_balancer.test_load_balancer.id
    protocol = "https"
    listen_port = 443
    destination_port = 80
    http {
         certificates = [hcloud_managed_certificate.managed_cert.id]
   }
}
```

More Details: https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/load_balancer_service

**Comment by StarpTech** [comment]
oh, great, thank you!
