### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by afandian** [hetznercloud/terraform-provider-hcloud#45]
[README.md](https://github.com/hetznercloud/terraform-provider-hcloud/blob/master/README.md)'s "Using the provider" links to [docs/readme.md](https://github.com/hetznercloud/terraform-provider-hcloud/blob/master/docs/readme.md) but this file is empty. It points to ERB templates in the [/website](https://github.com/hetznercloud/terraform-provider-hcloud/tree/master/website) directory, but I can't find the compiled documentation anywhere. 

Are the Terraform docs available?

**Comment by thetechnick** [comment]
Hi @afandian!
because of #41 I changed the documentation format to the erb templates,
but until this provider is officially approved by HashiCorp there is no rendered version of the documentation.

You can browse through the latest markdown docs when going back a few commits:
https://github.com/hetznercloud/terraform-provider-hcloud/tree/208a0ac81e1e3ee06f9b9a4c7dffe6c64a7e88df/docs

**Comment by thetechnick** [comment]
You can find the documentation here now https://www.terraform.io/docs/providers/hcloud/index.html
