### ISSUE TITLE
[Bug]: *All* firewall rules shown on `terraform apply`, even when I add just *one* `description`

### ISSUE THREAD

**Issue by ThomasLandauer** [hetznercloud/terraform-provider-hcloud#453]
### What happened?

version = "1.30.0"

I'm just adding this to *one* firewall rule:
```
description = "foobar"
```
Then, on `terraform apply` I get *all* my firewall rules listed for deletion, and for creation - this is several screens long. But at the bottom it says:
> Plan: 0 to add, 1 to change, 0 to destroy.

Might be related to the new version (1.30.0) or to the new feature (firewall descriptions).

### What did you expect to happen?

Just this one change ;-)

### Please provide a minimal working example

```
resource "hcloud_firewall" "app" {
    name = "app"
    rule {
        direction  = "in"
        protocol   = "icmp"
        port       = ""
        source_ips = ["::/0"]
        # description = "foobar"
    }
    rule {
        direction  = "in"
        protocol   = "tcp"
        port       = "22"
        source_ips = ["::/0"]
    }
}
```

**Comment by fhofherr** [comment]
Hi,

unfortunately this is not possible. Due to the way our firewalls work we do not allow modifying individual firewall rules. Therefore the `hcloud_firewall` resource always needs to drop and re-create all rules as soon as you change one rule. Unfortunately this results in the changes you mentioned being shown.
