### ISSUE TITLE
[Bug]: importing an existing hcloud_server forces a destruction/creation of the resource

### ISSUE THREAD

**Issue by uovobw** [hetznercloud/terraform-provider-hcloud#471]
### What happened?

This is the same issue as https://github.com/hetznercloud/terraform-provider-hcloud/issues/278 that has been closed with no resolution, even though a number of other users other than the original reported have reported the same issue. i have commented as well but could not re-open the issue, so i am opening a new one, sorry for the noise but this is _severely_ limiting our terraform adoption in a 15+ account with tens of servers. 
The import succeeds, but then the server is forever marked as `must be replaced` because the image that was used in creating it no longer exists.

### What did you expect to happen?

An import of an hcloud_server without having to rebuild it from a provided image

### Please provide a minimal working example

terraform versions
```
Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hetznercloud/hcloud v1.31.1
....
```

```
resource "hcloud_server" "gateway" {
  name = "gateway"
  delete_protection  = true
  keep_disk = false
  rebuild_protection = true
  location = "fsn1"
  image = "THIS IS THE PROBLEM"
  server_type = "cx21"
  backups = true
}
```

**Comment by fhofherr** [comment]
Hi @uovobw,

issue #278 was not closed without a resolution. The underlying issue of #278 was that we did not retain references to deleted images up to the change mentioned in that issue. Since this change is deployed such references are retained and our API returns the IDs of the deleted images. However, if the image of your servers has been deleted before that change we simply do not have that reference anymore. As such we cannot restore it.

Suppressing a change in the image field by default is no viable option from our point of view either. We have no way of making a distinction between legitimate cases, where a server recreate is desired, and those cases where we need to suppress the diff.

As mentioned in #278 it should be possible for you to keep Terraform from trying to re-create your imported servers, by adding the following to the affected definitions:

```
lifecycle {
  ignore_changes = [ image ]
}
```
