### ISSUE TITLE
Volume attachment errors with "cannot perform operation because server is locked (locked)"

### ISSUE THREAD

**Issue by tjung** [hetznercloud/terraform-provider-hcloud#53]
I'm trying to dynamically attach multiple volumes to a database server with Terraform, but it errors because the resource (server) is not available yet to attach the second volume. It errors with:

"cannot perform operation because server is locked (locked)"

I've tried to delay the attachment until the first volume was fully attached and done, but no succes. I think it would be better that the Hetzner Cloud provider adds a retry helper in it's API for volumes -> https://www.terraform.io/docs/extend/resources.html#retry

**Comment by LKaemmerling** [comment]
Which version do you have? This problem should be fixed as of Version 1.15

**Comment by LKaemmerling** [comment]
After testing it a bit, i can confirm this bug. I'm working on a fix.

**Comment by LKaemmerling** [comment]
For your specific use case (1 server: n volumes) I would recommend you to use the `hcloud_volume_attachment` resource. I will release a version 1.6.0 shortly, it contains the fix for the error you mentioned on the `hcloud_volume_attachment` resource.

**Comment by LKaemmerling** [comment]
Provider 1.6.0 was released. @tjung can you please try again (with the `hcloud_volume_attachment` resource)

**Comment by tjung** [comment]
Hi @LKaemmerling,

Can confirm it works now in version 1.6! 

No errors anymore and all volumes attached. Sorry for not mention that I was using version **1.5** and already using resource **hcloud_volume_attachment** to attach volumes to servers.

Tx.

**Comment by tjung** [comment]
Checked your source code changes and saw the note below. I tested with server_id and it also works, why would you use the 'location' argument instead of 'server_id' argument?


_**Note:** When you want to add multiple volumes to a server, please use the `hcloud_volume_attachment` resource and the `location` argument instead of the `server_id` argument._

**Comment by LKaemmerling** [comment]
You can create a volume with a server (server_id) or with a location. When you create two volumes at the same time with the server_id, it will throw an error on the attaching step for the second volume because the server is locked (it is in the progress of attaching the first volume).
This will fail with the message you provided in the first post. 

The hcloud_volume_attachment retries it now, so it can not fail with this error. On Volume Create side, i can not "fix" this, because the attachment after create is handled by our backend, not by terraform.
