### ISSUE TITLE
[Feature]: ability to chose project where resources are created 

### ISSUE THREAD

**Issue by slav123** [hetznercloud/terraform-provider-hcloud#649]
### What whould you like to see?

As a user, I would like to be able to choose a project where my resources are created. Currently, I can't see a place for it anywhere

**Comment by apricote** [comment]
Hey @slav123,

all resources are created in the project that is associated with the API Token. To manage multiple projects in the same terraform configuration, you can create multiple `providers` with different API Tokens:

```terraform
provider "hcloud" {
  alias  = "dev"
  token = var.hcloud_token_dev
}

provider "hcloud" {
  alias  = "prod"
  token = var.hcloud_token_prod
}

resource "hcloud_server" "web_dev" {
  # Specify which provider to use
  provider = hcloud.dev

  # Everything else
  # ...
}

resource "hcloud_server" "web_prod" {
  # Specify which provider to use
  provider = hcloud.prod

  # Everything else
  # ...
}
```

Read more about this on the [official terraform docs](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations).

I hope this provides the functionality you are looking for, otherwise please just comment what you are missing :)

**Comment by slav123** [comment]
Perfect - I could find this information anywhere. Thanks .

**Comment by apricote** [comment]
You can also find more information about our API tokens in the [API docs](https://docs.hetzner.cloud/#getting-started):

> A token is bound to a Project, to interact with the API of another Project you have to create a new token inside the Project.
