### ISSUE TITLE
[Bug]: Inconsistent plan when dynamic network block is used

### ISSUE THREAD

**Issue by pellepelster** [hetznercloud/terraform-provider-hcloud#707]
### What happened?

When applying a project I get the following message
```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.some_server.hcloud_server.some_server to include new values learned so far during apply, provider
│ "registry.terraform.io/hetznercloud/hcloud" produced an invalid new value for .network: actual set element
│ cty.ObjectVal(map[string]cty.Value{"alias_ips":cty.UnknownVal(cty.Set(cty.String)), "ip":cty.StringVal("10.0.1.1"),
│ "mac_address":cty.UnknownVal(cty.String), "network_id":cty.NumberIntVal(3.07527e+06)}) does not correlate with any element in plan.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.some_server.hcloud_server.some_server to include new values learned so far during apply, provider
│ "registry.terraform.io/hetznercloud/hcloud" produced an invalid new value for .network: block set length changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### What did you expect to happen?

I expected the apply to work properly.

### Please provide a minimal working example

**main.tf**
```
terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.41.0"
    }
  }
}

provider "hcloud" {}

resource "hcloud_network" "some_network" {
  ip_range = "10.0.0.0/16"
  name     = "some-network"
}

resource "hcloud_network_subnet" "some_subnet" {
  ip_range     = "10.0.1.0/24"
  network_id   = hcloud_network.some_network.id
  network_zone = "eu-central"
  type         = "cloud"
}

module "some_server" {
  source = "./instance"

  network_id = hcloud_network.some_network.id
  network_ip = "10.0.1.1"
}
```

**instance/main.tf**

```
terraform {
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.40.0"
    }
  }
}

variable "network_id" {}

variable "network_ip" {}

locals {
  networks = var.network_id > 0 && var.network_ip != null ? [
    { network_id : var.network_id, network_ip : var.network_ip }
  ] : []
}

resource "hcloud_server" "some_server" {

  name        = "some-server"
  image       = "debian-11"
  server_type = "cx11"
  location    = "fsn1"

  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }

  dynamic "network" {
    for_each = local.networks

    content {
      network_id = network.value.network_id
      ip         = network.value.network_ip
    }
  }
}
```

I found the following steps to lead to an repeatable reproduce:

* start with an empty account and no local terraform state
* run `terraform apply`
* it seems like it works on the second `terraform apply` run

**Comment by apricote** [comment]
Hey @pellepelster, I was unable to reproduce this locally. What version of terraform & the provider are you running? Could you generate debug logs for the full run and send them to me `julian.toelle <at> hetzner-cloud.de`?

```
TF_LOG=TRACE TF_LOG_PATH=gh-707.tf terraform apply
```

**Comment by pellepelster** [comment]
@apricote  That is weird, I just tried it on another machine and it failed immediately. Terraform version is
```
$ terraform -version                                                                                                                                
Terraform v1.5.0
on linux_amd64
+ provider registry.terraform.io/hetznercloud/hcloud v1.41.0
```

see attached logfile for the requested trace.

[gh-707.log](https://github.com/hetznercloud/terraform-provider-hcloud/files/11936516/gh-707.log)

**Comment by apricote** [comment]
Okay, I tested it without the module. If I have the module indirection it fails immediately.

I am not sure if this bug is actually from the provider. What happens:

- On the first apply, server & network do not exit
- This passes (I dont understand why) a `0` as the `network_id` when planning the module
- Because of your `networks` local, this means that the plan for `hcloud_server` does not include the `network` block
- When actually executing the plan, network & subnet are created and a new plan for the module is made with the proper network ID.
- This fails because now a network block shows up

I fixed this by removing the check for `var.network_id > 0` in the local:

```diff
 locals {
-  networks = var.network_id > 0 && var.network_ip != null ? [
+  networks = var.network_ip != null ? [
     { network_id : var.network_id, network_ip : var.network_ip }
   ] : []
 }
```

Please note, that you should make sure that the subnet is created before adding the server to the network with an IP from the subnet. This can be done by adding a `depends_on = [ hcloud_network_subnet.some_subnet ]` to the module or the `hcloud_server` resource. See [this example](https://registry.terraform.io/providers/hetznercloud/hcloud/latest/docs/resources/server#server-creation-with-network)

**Comment by pellepelster** [comment]
Hi, that seems to solve the immediate problem, thanks for the analysis and the solution
