### ISSUE TITLE
[Bug]: ssh_keys on hcloud_server replaces the whole server

### ISSUE THREAD

**Issue by thereisnotime** [hetznercloud/terraform-provider-hcloud#737]
### What happened?

I must voice my profound dismay and disbelief at the decision to replace the entire server when adding a new key to ssh_keys. To say that this decision is misguided would be a **gross** understatement.

This behavior is not just unconventional; it's **utterly nonsensical**. When I discovered that adding a new SSH key resulted in the recreation of **the whole server**, I was left aghast. In all my years of working with various cloud platforms, I have never encountered such an illogical and disruptive implementation.

To liken this to a real-world scenario, it is akin to demolishing an entire house just to change the lock on the front door. It is not merely counterintuitive; it is downright absurd.

I have to question what considerations were made when deciding on this implementation. It defies industry standards, common sense, and practical usability. This is not just an inconvenience; it's a critical flaw that could have far-reaching consequences.

I urgently request a detailed explanation for this design choice, along with a swift reassessment. The current implementation is not only out of step with professional cloud practices but potentially damaging to user trust and workflow efficiency.

I expect this matter to be treated with the seriousness it deserves, and I look forward to a satisfactory resolution.

### What did you expect to happen?

I expect that the key is just added to the host/s via cloudinit and not destroy the whole server with all of its data.

### Please provide a minimal working example

```
resource "hcloud_server" "vm_vampi" {
  name        = "${local.env}-vampi"
  server_type = local.vm_vampi_server_type
  image       = local.vm_vampi_image
  datacenter  = local.vm_vampi_datacenter
  network {
    network_id = hcloud_network.infra01.id
    ip         = local.vm_vampi_int_ip
  }
  public_net {
    ipv4_enabled = true
    ipv6_enabled = true
  }

  ssh_keys = local.vm_vampi_root_keys
  labels   = local.tags
  depends_on = [
    hcloud_network_subnet.a
  ]


}
```

**Comment by apricote** [comment]
Hey @thereisnotime,

## Conduct

Your message is insulting and demeaning towards the people working on this. We do not allow such conduct in our projects, so please refrain from doing that again.

## Background

### Cloud-Init

The ssh keys are setup on the server by cloud-init. The `SSH` module in cloud-init is only executed once per instance/server ([source](https://github.com/canonical/cloud-init/blob/1e1624ff8f11df36855f9795f260b39543b070f7/cloudinit/config/cc_ssh.py#L131C1-L131C31)). So even if we would provide new data to cloud-init, it would not update the `authorized_keys`.

### Hetzner Cloud API

Our API does not provide a way to update the SSH Keys for existing servers, as that is not supported by cloud-init. This is mentioned in our docs: [_I have added my SSH key to the Cloud Console, why can I not access my existing server via my SSH key?_](https://docs.hetzner.com/cloud/servers/faq/#i-have-added-my-ssh-key-to-the-cloud-console-why-can-i-not-access-my-existing-server-via-my-ssh-key)

### Terraform

Terraform works declaratively. It tries to adjust the world to your specification. As there is no way to update the SSH Keys through the API, there is no way for us to change the keys without recreating the server. The other solution would be to crash/not allow this at all, but this goes against the terraform way.

Terraform does notify you that this is happening in the plan:

```terraform
Terraform will perform the following actions:

  # hcloud_server.tf_737 must be replaced
-/+ resource "hcloud_server" "tf_737" {
      + backup_window              = (known after apply)
      ~ datacenter                 = "fsn1-dc14" -> (known after apply)
      ~ firewall_ids               = [] -> (known after apply)
      ~ id                         = "1234" -> (known after apply)
      ~ ipv4_address               = "128.140.112.137" -> (known after apply)
      ~ ipv6_address               = "2a01:4f8:c17:932d::1" -> (known after apply)
      ~ ipv6_network               = "2a01:4f8:c17:932d::/64" -> (known after apply)
      - labels                     = {} -> null
        name                       = "gh-737"
      ~ ssh_keys                   = [ # forces replacement
          + "my-key"
        ]
      ~ status                     = "running" -> (known after apply)
        # (9 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

## Other Cloud Providers

Recreating the server when SSH Keys change is in line to other Cloud Providers:

- [`azurerm_linux_virtual_machine`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#admin_ssh_key)
  - > [admin_ssh_key](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#admin_ssh_key) - (Optional) One or more admin_ssh_key blocks as defined below. Changing this forces a new resource to be created.
- [`digitalocean_droplet`](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/droplet#ssh_keys)
  - > [ssh_keys](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/droplet#ssh_keys) - (Optional) A list of SSH key IDs or fingerprints to enable in the format [12345, 123456]. To retrieve this info, use the [DigitalOcean API](https://docs.digitalocean.com/reference/api/api-reference/#tag/SSH-Keys) or CLI (doctl compute ssh-key list). Once a Droplet is created keys can not be added or removed via this provider. Modifying this field will prompt you to destroy and recreate the Droplet.
- [`linode_instance`](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance#authorized_keys)
  - > [authorized_keys](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/instance#authorized_keys) - (Optional with image) A list of SSH public keys to deploy for the root user on the newly created Linode. This value can not be imported. Changing authorized_keys forces the creation of a new Linode Instance.

There are some cloud providers that do in fact support updating the SSH Keys, but they usually have an agent that you need to have installed for this to work. See for example the [AWS Systems Manager SSM Agent](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-prerequisites.html). We have no such agent.

## Workarounds

### Ignoring Changes to `ssh_keys`

If you never want to replace a server because your SSH Keys change, you can tell Terraform this through [`lifecycle.ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes):

```terraform
resource "hcloud_server" "tf_737" {
  name        = "gh-737"
  image       = "ubuntu-22.04"
  server_type = "cpx11"
  location    = "fsn1"

  ssh_keys           = [your-ssh-keys]

  lifecycle {
    ignore_changes = [ssh_keys]
  }
}
```

### Manually updating the SSH Keys through Terraform

You can use a [`null_resource`](https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource) and the [`remote-exec` provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/remote-exec) to update the SSH Keys of existing servers in Terraform.

### Manually updating the SSH Keys through Ansible

Similar to the solution above, you can also use our Ansible Inventory & `ansible.posix.authorized_key` to achieve the same:

```yaml
- name: Set servers ssh authorized keys for root user
  hosts: my-servers
  tasks:
    - name: Set authorized key from hcloud ssh key
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "ssh-rsa AAAjjk76kgf...Xt"
```

## Follow Up Actions

We did not document this behaviour in our Terraform provider docs. I have opened #738 to explain this behaviour in our docs.

I have also added 6 votes (you + 5 upvotes on the issue here) to our internal feedback issue on "Updating SSH Keys for existing servers through API".

**Comment by maartenbeeckmans** [comment]
It's also a good idea to add prevent_destroy to your servers to make sure this won't happen by accident.

```terraform
lifecycle {
  prevent_destroy = true
}
```

**Comment by apricote** [comment]
Closing as we updated the docs and provided some alternatives.
