### ISSUE TITLE
Can't downgrade from CX21 to CX11

### ISSUE THREAD

**Issue by Somebi** [hetznercloud/terraform-provider-hcloud#80]
getting error:

* hcloud_server.redis: 1 error(s) occurred:
* hcloud_server.redis: cannot change type because the selected server_type has not sufficient disk space (invalid_server_type)

Have to first taint it manually and then deploy.

**Comment by LKaemmerling** [comment]
You can not downgrade a server from a higher plan to a lower plan if the disk size is higher than in the smaller plan..

As sample:
You can not downgrade a CX21 to a CX11 in the normal case.
You can only downgrade a CX21 when you have upgraded it from a CX11 before and used the `keep_disk` option. 

CX11 ( 20 GB Disk) --> Upgrade with `keep_disk` = true --> CX21(20 GB Disk instead of 40 GB Disk) --> Downgrade to CX 11 --> CX11 (With 20 GB Disk).

**Comment by Somebi** [comment]
Oh, ty, didn't knew there was such option out there

пн, 8 апр. 2019 г., 13:49 Lukas Kämmerling <notifications@github.com>:
