### ISSUE TITLE
[Feature]: Support for Project resource

### ISSUE THREAD

**Issue by romerojunior** [hetznercloud/terraform-provider-hcloud#934]
### What whould you like to see?

Are there any plans to support the project resource (as in the one available at https://console.hetzner.cloud/projects)? Interestingly, I cannot find any reference for the project resource in the API calls to, for example, the https://api.hetzner.cloud/v1/networks endpoint, the payload on the POST request makes no reference to it. What sort of magic is behind the project?

**Comment by romerojunior** [comment]
I guess I understand it, the authorization towards the provider is done with a token which maps to the project (as in, a pre-requisite), which comes with the simplicity of resources being unaware of the project's existence, making it irrelevant to Terraform.

**Comment by achivi** [comment]
@romerojunior Actually for our use case, we do see a benefit of project related configs, mostly around the members space. especially because hetzner does not support 3rd party IDP login, we need some kind of way to control the members at scale. 

And of course we would love to see project creation with some org wide token to make our pipelines 100% automatic :) similar to TF workspaces under org.

**Comment by jooola** [comment]
> And of course we would love to see project creation with some org wide token to make our pipelines 100% automatic :) similar to TF workspaces under org.

I have upvoted the public project API feature on our internal tracker.
