### ISSUE TITLE
[Bug]: `hcloud_load_balancer_target` import failed if the target is `ip`

### ISSUE THREAD

**Issue by ioah86** [hetznercloud/terraform-provider-hcloud#961]
### What happened?

Running a vanilla import with a file with contents of this type
```
import {
  to = hcloud_load_balancer_target.NAME123__ip__x_x_x_x
  id = "12345__ip__1.1.1.1"
}
```
(names and IPs are obfuscated for this example).

The command I was running was

```
terraform plan -generate-config-out=generated_resources.tf
```

Then an error occurred stating

```
"ip": conflicts with use_private_ip
```

From the documentation, I understand that if the target type is `ip`, then there should be no field `use_private_ip`. However, the field pops up in the generated terraform file, and subsequently causes the `plan` phase to fail.

### What did you expect to happen?

I expected the import to have no problem when running
```
terraform plan -generate-config-out=generated_resources.tf
```

### Please provide a minimal working example

The example above with a valid IP and resource_id is a minimum working example for this bug.

**Comment by apricote** [comment]
Hey @ioah86,

it looks like this comes from the loose way we interpret the Terraform provider contract. This was not an issue before, because Terraform hid those issues from users, but newer features tend to cause issues with this. We have a full refactoring on our backlog (#752) which should highlight these issues whenever we work on a resource from that list.

I have fixed this specific issue in #962, but there are probably more resources and fields with this problem in the provider, so please keep opening issues if you find anything.
